name: Update lock file

on:
  push:
    branches:
      - "release-please-**"

jobs:
  update-pr:
    permissions:
      contents: write
    name: update-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 16
      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2
        with:
          version: 8
      - run: pnpm install --lockfile-only
      - name: commit
        run: |
          git config --global user.name "release-please[bot]"
          git config --global user.email "55107282+release-please[bot]@users.noreply.github.com"
          git add pnpm-lock.yaml
          git commit -m "Update lock file" --no-verify
          git push origin --no-verify
